AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: API Gateway with Cognito Authorization

Parameters:
  UserPoolArn:
    Type: String
    Description: ARN of the Cognito User Pool
    Default: "arn:aws:cognito-idp:eu-north-1:565393034649:userpool/eu-north-1_YxTYEALZB"
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
    Description: Environment type (dev or prod)
  OpenAIAPIKey:
    Type: String
    Description: OpenAI API Key for LLM access
    NoEcho: true # This prevents the key from being displayed in logs/console

Globals:
  Api:
    Cors:
      AllowMethods: "'GET,PUT,POST,PATCH,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Origin'"
      AllowOrigin: !If
        - IsDev
        - "'*'"
        - "'https://smartstudentadvisor.nl'"
    Auth:
      Authorizers:
        UpdatedApiAuth:
          UserPoolArn: !Ref UserPoolArn
          AuthType: COGNITO_USER_POOLS
          Identity:
            Header: Authorization

Resources:
  ApiGatewayCloudWatchLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

    ApiGatewayAccount:
      Type: AWS::ApiGateway::Account
      Properties:
        CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchLogsRole.Arn

  ApiGatewayStageProdSettings:
    Type: AWS::ApiGateway::MethodSettings
    Properties:
      RestApiId: !Ref ServerlessRestApi
      StageName: Prod
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/hello_handler.lambda_handler
      Runtime: python3.12
      CodeUri: .
      Environment:
        Variables:
          Environment: !Ref Environment
      Events:
        HelloEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            # Auth:
            #   Authorizer: UpdatedApiAuth

  GoodbyeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/goodbye_handler.lambda_handler
      Runtime: python3.12
      CodeUri: .
      Environment:
        Variables:
          Environment: !Ref Environment
      Events:
        ByeEvent:
          Type: Api
          Properties:
            Path: /goodbye/bye
            Method: GET
            Auth:
              Authorizer: UpdatedApiAuth
        SeeyaEvent:
          Type: Api
          Properties:
            Path: /goodbye/seeya
            Method: GET
            Auth:
              Authorizer: UpdatedApiAuth

  DatabaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/database_handler.lambda_handler
      Runtime: python3.12
      Timeout: 10
      CodeUri: .
      Environment:
        Variables:
          Environment: !Ref Environment
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${Environment}-student-advisor-table"
      Events:
        PutStudent:
          Type: Api
          Properties:
            Path: /student
            Method: PUT
            Auth:
              Authorizer: UpdatedApiAuth
        GetStudent:
          Type: Api
          Properties:
            Path: /student
            Method: GET
            Auth:
              Authorizer: UpdatedApiAuth
        PatchStudent:
          Type: Api
          Properties:
            Path: /student
            Method: PATCH
            Auth:
              Authorizer: UpdatedApiAuth

  TokenUsageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/token_usage_handler.lambda_handler
      Runtime: python3.12
      CodeUri: .
      Environment:
        Variables:
          Environment: !Ref Environment
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${Environment}-student-advisor-table"
      Events:
        UploadTokenUsage:
          Type: Api
          Properties:
            Path: /token-usage
            Method: POST
            Auth:
              Authorizer: UpdatedApiAuth
        GetTokenUsage:
          Type: Api
          Properties:
            Path: /token-usage
            Method: GET
            Auth:
              Authorizer: UpdatedApiAuth

  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/chat_handler.lambda_handler
      Runtime: python3.12
      Timeout: 10
      CodeUri: .
      Environment:
        Variables:
          Environment: !Ref Environment
          OPENAI_API_KEY: !Ref OpenAIAPIKey
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${Environment}-student-advisor-table"
      Events:
        ChatEvent:
          Type: Api
          Properties:
            Path: /chat
            Method: POST
            Auth:
              Authorizer: UpdatedApiAuth
        CheckStudentEvent:
          Type: Api
          Properties:
            Path: /student/check
            Method: GET
            Auth:
              Authorizer: UpdatedApiAuth

Outputs:
  ApiUrl:
    Description: "URL of the API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

Conditions:
  IsDev: !Equals
    - !Ref Environment
    - dev
