Transform: AWS::Serverless-2016-10-31

Parameters:
  EnvironmentType:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  StageNameParameter:
    Type: String
    Default: dev
    Description: API Gateway stage name

Resources:
  MyBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          ALLOWED_ORIGIN: !If
            - IsDev
            - "*"
            - "https://d10tb7qqmyl8u1.cloudfront.net"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: GET

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageNameParameter
      EndpointConfiguration: REGIONAL

Conditions:
  IsDev: !Equals [!Ref EnvironmentType, "dev"]
