AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Simple API Gateway with Python Lambda Function.

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Events:
        HelloEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            Auth:
              Authorizer: MyLambdaAuthorizer

  MyLambdaAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: authorizer.authorizer.lambda_handler
      Runtime: python3.9
      CodeUri: authorizer/

Outputs:
  ApiUrl:
    Description: "URL of the API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
