name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov moto boto3
          pip install -r requirements.txt

      - name: Run tests
        working-directory: backend
        run: |
          pytest tests/ -v --cov=services

  build-backend:
    runs-on: ubuntu-latest
    needs: [test-backend]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install AWS SAM CLI
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli

      - name: Build Backend with SAM
        working-directory: backend
        run: sam build

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: backend/.aws-sam/build

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install & Build NextJS
        working-directory: llm_advisor_app
        run: |
          npm install
          npm run build

      - name: Copy Files to LightSail (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: |
            llm_advisor_app
          target: /home/ubuntu/frontend

      - name: Finalize deployment
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd /home/ubuntu/frontend/llm_advisor_app
            # Restart PM2 process
            pm2 stop advisor_app || true
            pm2 start npm --name "advisor_app" -- start

  deploy-backend:
    runs-on: ubuntu-latest
    needs: [build-backend]
    environment: production
    steps:
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: backend/.aws-sam/build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Backend with SAM
        working-directory: backend
        run: |
          sam deploy --stack-name my-backend-stack \
            --capabilities CAPABILITY_IAM \
            --region ${{ secrets.AWS_REGION }} \
            --s3-bucket artifacts-llm-advisor-cloudform \
            --no-confirm-changeset \
            --parameter-overrides "Environment=prod OpenAIAPIKey=${{ secrets.OPENAI_API_KEY }}" \
            --no-fail-on-empty-changeset
